workspace:
  base: /go
  path: src/github.com/Hundemeier/simple-audio

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: golang
    group: dep
    commands:
      - go get -v -d #only download and not build

  frontend:
    image: node
    group: dep
    commands:
      - cd webgui/
      - npm install
      - npm run build
  
  pre-build:
    image: golang
    commands:
      - go get github.com/jteeuwen/go-bindata/...
      - go get github.com/elazarl/go-bindata-assetfs/...
      - go-bindata-assetfs webgui/dist/...
  
  build-win-64:
    image: golang
    group: build
    commands:
      - GOOS=windows GOARCH=amd64 go build -o out/simpleAudio_win_amd64.exe

  build-win-32:
    image: golang
    group: build
    commands:
      - GOOS=windows GOARCH=386 go build -o out/simpleAudio_win_386.exe

  build-linux-64:
    image: golang
    group: build
    commands:
      - apt update && apt install -y libasound2-dev
      - GOOS=linux GOARCH=amd64 go build -o out/simpleAudio_linux_amd64

  discord:
    image: appleboy/drone-discord
    group: upload
    secrets: [ discord_webhook_id, discord_webhook_token ]
    message: |
      {{ repo.name }}: {{ build.status }}
      author: {{build.author}} on branch {{build.branch}} with {{build.commit}}
      build: {{build.number}} after {{build.event}}
      {{build.link}}

  code-analysis:
    image: aosapps/drone-sonar-plugin
    group: upload
    secrets: [sonar_host, sonar_token]
    commands:
      - apk update && apk add --no-cache git

  github_release:
    image: plugins/github-release
    group: upload
    files: out/*
    secrets: [ github_token ]
    draft: true
    when:
      event: tag

  upload_webdav_win64:
    image: vividboarder/drone-webdav
    group: upload
    file: out/simpleAudio_win_amd64.exe
    destination: https://nextcloud.helmutzett.p7.de:10000/remote.php/dav/files/drone/uploads/
    secrets: [webdav_username, webdav_password]

  upload_webdav_win32:
    image: vividboarder/drone-webdav
    group: upload
    file: out/simpleAudio_win_386.exe
    destination: https://nextcloud.helmutzett.p7.de:10000/remote.php/dav/files/drone/uploads/
    secrets: [webdav_username, webdav_password]

  upload_webdav_linux64:
    image: vividboarder/drone-webdav
    group: upload
    file: out/simpleAudio_linux_amd64
    destination: https://nextcloud.helmutzett.p7.de:10000/remote.php/dav/files/drone/uploads/
    secrets: [webdav_username, webdav_password]