workspace:
  base: /go
  path: src/github.com/Hundemeier/simple-audio

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: golang
    group: dep
    commands:
      #- apt update && apt install -y libasound2-dev
      - go get -v -d #only download and not build

  frontend:
    image: node
    group: dep
    commands:
      - cd webgui/
      - npm install
      - npm run build
  
  build:
    image: golang
    commands:
      - go get github.com/jteeuwen/go-bindata/...
      - go get github.com/elazarl/go-bindata-assetfs/...
      - go-bindata-assetfs webgui/dist/...
      - GOOS=windows GOARCH=amd64 go build -o out/simpleAudio_win_amd64.exe