workspace:
  base: /go
  base: /
  path: src/github.com/Hundemeier/simple-audio

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: golang
    commands:
      - apt update && apt install -y libasound2-dev node
      - go get -v -d #only download and not build
      - cd webgui/
      - npm install
      - cd ..
      - go test -v .
      - ./build.sh