workspace:
  base: /go
  base: /alsa
  path: src/github.com/Hundemeier/simple-audio

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: golang
    group: dep
    commands:
      - apt update && apt install -y libasound2-dev
      - go get -v -d #only download and not build

  frontend:
    image: node
    group: dep
    commands:
      - cd webgui/
      - npm install
      - npm run build
  
  build:
    image: golang
    commands:
      - ./build.sh