workspace:
  base: /go
  path: src/github.com/Hundemeier/simple-audio

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: golang
    group: pre-build
    commands:
      - apt update && apt install -y libasound2-dev
      - go get

  frontend:
    image: node
    group: pre-build
    commands:
      - npm install
#      - npm run build

  testing:
    image: golang
    commands:
      - go test -v .

  build:
    image: golang
    commands:
      - go build